name: Build Docker image
on:
  workflow_call:
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: mvn spring-boot:build-image