name: Build with Maven
on:
  workflow_call:
    secrets:
      password:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Configure Maven settings.xml with PAT
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: '[{ "id": "github-quidli", "username": "${{ username }}", "password": "${{ password }}" }]'
      - name: Build with Maven
        run: mvn -B -U package --file pom.xml