name: Build and publish Docker image
on:
  workflow_call:
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # so the dependencies may be downloaded from GitHub artifact repository
      - name: Configure Maven settings.xml with PAT
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: '[{ "id": "github-quidli", "username": "${{ secrets.username }}", "password": "${{ secrets.password }}" }]'
      - name: Configure image name and version
        run: |
          echo "GROUP_ID=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)" >> $GITHUB_ENV
          echo "ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Build the Docker image
        run: |
          mvn spring-boot:build-image -Dspring-boot.build-image.imageName=ghcr.io/${{ env.GROUP_ID }}/${{ env.ARTIFACT_ID }}:${{ env.RELEASE_VERSION }}
          docker push ghcr.io/${{ env.GROUP_ID }}/${{ env.ARTIFACT_ID }}:${{ env.RELEASE_VERSION }}