name: Publish to GitHub Packages
on:
  workflow_call:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Configure Maven settings.xml with PAT
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: '[{ "id": "github-quidli", "username": "lmarqueze@gmail.com", "password": "${{ secrets.PAT }}" }]'
      - name: Publish package
        run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
